"""Paths and markers for the codebase wiki platform."""

from __future__ import annotations

WIKI_ROOT = "wiki/codebase"
MODULES_DIR = "modules"
SYSTEM_DIR = "system"
RUNS_DIR = "runs"
GRAPH_DIRNAME = "graph"
GRAPH_JSON = "graph.json"
CONFIG_REL = ".pipeline/docs-modules.yaml"
AGENTS_START = "<!-- pipeline-kit:codebase-docs start -->"
AGENTS_END = "<!-- pipeline-kit:codebase-docs end -->"
DEFAULT_WORKERS = 4

MODULES_TEMPLATE = """\
# Module inventory for monorepo documentation (pipeline-kit).
# Own this file: paths must match real business domains.
# CLI: pipeline-kit docs init-modules | extract-modules | merge-modules | status
#
# modules:
#   - id: billing
#     name: Billing service
#     path: services/billing
#     tech: [java, spring]
#     enabled: true

modules: []
"""

WIKI_README = """\
# Codebase wiki

Monorepo knowledge for agents and humans: **per-module graphs and documentation**.

| Attribute | Value |
|-----------|--------|
| Type | Handbook |
| Audience | Humans and agents documenting or reviewing modules |
| Adapt | Fill `.pipeline/docs-modules.yaml`, then run `pipeline-kit docs extract-modules` |

## Layout

- `INDEX.md` — module table (router)
- `modules/{id}/` — docs (`README.md`, …) and `graph/graph.json`
- `system/` — optional cross-module architecture after merge
- `runs/` — extract/doc run manifests

This tree is **not** the pack lesson wiki at `.pipeline/wiki/` (short retro lessons).

## Refresh

```bash
pipeline-kit docs extract-modules
pipeline-kit docs link-index
# optional:
pipeline-kit docs merge-modules
pipeline-kit docs link-agents
```

In chat: ask to **document the large codebase** / **run large-codebase-docs**.

## Git

Prefer committing markdown under `modules/` and `INDEX.md`. Large `graph/graph.json` files may be gitignored and regenerated.
"""

INDEX_HEADER = """\
# Codebase modules

| Attribute | Value |
|-----------|--------|
| Type | Wiki index |
| Audience | Parent and specialists when routing monorepo knowledge |
| Adapt | Regenerated by `pipeline-kit docs link-index` |

| Module | Name | Path | Graph | Docs | Security |
|--------|------|------|-------|------|----------|
"""
